name: gate

on:
  push:
    branches:
      - main
  pull_request:

env:
  PYTHON_VERSION: '3.11'

jobs:
  check-style:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: set up python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          cache: 'pipenv'
      - name: install dependencies
        run: |
          pip install pipenv
      - name: check style
        run: |
          pipenv install --dev
          pipenv run flake8

  run-unit-tests:
    runs-on: ubuntu-latest

    # https://docs.github.com/en/actions/using-containerized-services/creating-postgresql-service-containers
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - uses: actions/checkout@v4
      - name: set up python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          cache: 'pipenv'
      - name: install dependencies
        run: |
          pip install pipenv
      - name: run unit tests
        run: |
          pipenv install --dev
          SQLALCHEMY_DATABASE_URI=postgresql://postgres:postgres@localhost/postgres pipenv run \
          pytest --cov-report term --cov=app tests/unit
